### ISSUE TITLE
ImportError: cannot import name 'Instapaper'

### ISSUE THREAD

**Issue by lightjl** [mrtazz/InstapaperLibrary#5]
File "C:\Users\ADMINI~1\AppData\Local\Temp\pip-build-jzoz5tb4\instapaperlib\instapaperlib\__init__.py", line 3, in <module>
        from instapaperlib import Instapaper
    ImportError: cannot import name 'Instapaper'

pip install instapaperlib, it said ImportError.
I don't know why. I want to install instapaperlib, how can it from instapaperlib import Instapaper?
help, please.

**Comment by mrtazz** [comment]
what python version are you running this on?  what does your code look like? How do you run your code?
